/**
 * Nova skill registry — Phase 1–2 + ledger + residual queue/masters skills.
 * Dispatch is used from `runNovaTools`.
 */

import type { NovaSkill, NovaSkillHandlerContext, NovaSkillHandlerResult } from "@/lib/nova/skills/skill-contract";
import { novaPermissionsForTool } from "@/lib/ai/nova-tool-permissions";
import { runAttendanceLateSummary } from "@/lib/nova/skills/hr/attendance";
import {
  runOvertimeSummary,
  runRegularisationSummary,
} from "@/lib/nova/skills/hr/approvals";
import { runLeaveSummary } from "@/lib/nova/skills/hr/leave";
import { runSalarySummary } from "@/lib/nova/skills/hr/salary";
import { runStaffAdvancesSummary } from "@/lib/nova/skills/hr/advances";
import { runStaffSummary } from "@/lib/nova/skills/hr/staff";
import { runSalesSummary } from "@/lib/nova/skills/finance/sales";
import { runSalesOrdersSummary } from "@/lib/nova/skills/finance/sales-orders";
import { runPurchaseOrdersSummary } from "@/lib/nova/skills/finance/purchase-orders";
import { runReceiptsSummary } from "@/lib/nova/skills/finance/receipts";
import { runPaymentRequestsSummary } from "@/lib/nova/skills/finance/payment-requests";
import { runBankReconSummary } from "@/lib/nova/skills/finance/bank-recon";
import { runReceivablesSummary } from "@/lib/nova/skills/finance/receivables";
import { runStaffExpenseSummary } from "@/lib/nova/skills/finance/expenses";
import { runAccountsSnapshot } from "@/lib/nova/skills/finance/accounts-snapshot";
import { runGstrSnapshot } from "@/lib/nova/skills/finance/gstr-snapshot";
import { runDirectorDashboardSummary } from "@/lib/nova/skills/finance/director-dashboard";
import { runTallyStatus } from "@/lib/nova/skills/finance/tally-status";
import { runOrderBookSummary } from "@/lib/nova/skills/finance/order-book";
import { runReportsSnapshot } from "@/lib/nova/skills/finance/reports-snapshot";
import { runGstDocsSummary } from "@/lib/nova/skills/finance/gst-docs";
import { runProfitabilitySummary } from "@/lib/nova/skills/finance/profitability";
import { runOverdueInvoices } from "@/lib/nova/skills/finance/overdue-invoices";
import { runPurchaseBillsSummary } from "@/lib/nova/skills/finance/purchase-bills";
import { runBankAccountsSummary } from "@/lib/nova/skills/finance/bank-accounts";
import { runCreditNotesSummary } from "@/lib/nova/skills/finance/credit-notes";
import { runCustomerOutstanding } from "@/lib/nova/skills/finance/customer-outstanding";
import { runVendorsSummary } from "@/lib/nova/skills/finance/vendors";
import { runCustomersSummary } from "@/lib/nova/skills/finance/customers";
import { runPurchaseRequestsSummary } from "@/lib/nova/skills/finance/purchase-requests";
import { runCbgQuotationsSummary } from "@/lib/nova/skills/finance/cbg-quotations";
import { runCollectionDelayEstimate } from "@/lib/nova/skills/finance/collection-delay-estimate";
import { runKpiSummary, runKpiReport } from "@/lib/nova/skills/ops/kpi";
import { runTasksSummary } from "@/lib/nova/skills/ops/tasks";
import { runMyWorkSummary } from "@/lib/nova/skills/ops/my-work";
import { runStockSummary } from "@/lib/nova/skills/ops/stock";
import { runDeliverySummary } from "@/lib/nova/skills/ops/delivery";
import { runProjectsSummary } from "@/lib/nova/skills/ops/projects";
import { runIncentivesSummary } from "@/lib/nova/skills/ops/incentives";
import { runDailyBrief } from "@/lib/nova/skills/ops/daily-brief";
import {
  runCbgPipelineRecipe,
  runCollectionAttentionRecipe,
  runProjectHealthRecipe,
} from "@/lib/nova/recipes/registry";
import { runMonthPerformanceRecipe } from "@/lib/nova/packs/month-performance";
import { runProjectCommandRecipe } from "@/lib/nova/packs/project-command";
import { runCollectionAttentionPackRecipe } from "@/lib/nova/packs/collection-attention";
import { runAttendanceMonthRecipe } from "@/lib/nova/packs/attendance-month";
import { runCashBankingRecipe } from "@/lib/nova/packs/cash-banking";
import { runPendingWorkflowCounts } from "@/lib/nova/skills/ops/pending-workflow";
import { runApprovalsSummary } from "@/lib/nova/skills/ops/approvals-queue";
import { runGrnSummary } from "@/lib/nova/skills/ops/grn";
import { runProactiveInsights } from "@/lib/nova/skills/ops/proactive-insights";
import { runNovaAnalysisSkill } from "@/lib/nova/skills/ops/analysis";
import { runNovaTrendSkill } from "@/lib/nova/skills/ops/trend";
import { runDocumentsOpen } from "@/lib/nova/skills/system/documents-open";
import { runDocumentsSearch } from "@/lib/nova/skills/system/documents-search";
import { runNovaPulseSearch } from "@/lib/nova/skills/system/pulse-search";
import { runSettingsOpen } from "@/lib/nova/skills/system/settings-open";
import { runAppearanceOpen } from "@/lib/nova/skills/system/appearance-open";
import { runVendorBankOpen } from "@/lib/nova/skills/system/vendor-bank-open";
import { runNotificationsOpen } from "@/lib/nova/skills/system/notifications-open";
import { runWhatsappOpen } from "@/lib/nova/skills/system/whatsapp-open";
import { runPortalOpen } from "@/lib/nova/skills/system/portal-open";
import { runAutomationOpen } from "@/lib/nova/skills/system/automation-open";
import { runLinksOpen } from "@/lib/nova/skills/system/links-open";
import { runBankSmsOpen } from "@/lib/nova/skills/system/bank-sms-open";
import { runBackupOpen } from "@/lib/nova/skills/system/backup-open";
import { runSystemToolsOpen } from "@/lib/nova/skills/system/system-tools-open";
import { runAuditLogOpen } from "@/lib/nova/skills/system/audit-log-open";
import { runSearchEntities } from "@/lib/nova/skills/system/search-entities";
import { runEntity360 } from "@/lib/nova/entity-360";

const SKILLS_DEFS: NovaSkill[] = [
  {
    id: "hr.attendance",
    toolId: "attendance_late_summary",
    domain: "hr",
    label: "Attendance (late / present / absent)",
    description:
      "Attendance register summaries: late comers, present, absent, punch-out times, named-person punch status.",
    permissions: ["hr.attendance.read", "hr.attendance.team", "hr.punch.self"],
    riskLevel: "read",
    dataClasses: ["hr_attendance", "hr_pii"],
    intents: [
      "late comers",
      "who was late",
      "present today",
      "absent today",
      "did X punch",
      "punch out times",
    ],
    examples: [
      "late comers today",
      "who was absent yesterday",
      "was Zeeshan present today",
      "punch out time of all staffs",
      "attendance this week",
    ],
    preferDeterministic: true,
    handler: runAttendanceLateSummary,
  },
  {
    id: "hr.leave",
    toolId: "leave_summary",
    domain: "hr",
    label: "Leave balance / requests",
    description: "Leave pending, approved usage, entitlements, and upcoming leave.",
    permissions: [
      "hr.leave.read",
      "hr.leave.create",
      "hr.leave.approve",
      "hr.attendance.read",
      "hr.attendance.team",
    ],
    riskLevel: "read",
    dataClasses: ["hr_pii", "ops_summary"],
    intents: ["leave", "leave balance", "pending leave"],
    examples: ["leave balance", "my leave balance", "pending leave"],
    preferDeterministic: true,
    handler: runLeaveSummary,
  },
  {
    id: "hr.overtime",
    toolId: "overtime_summary",
    domain: "hr",
    label: "Overtime queue",
    description: "Pending / approved / rejected overtime records (team-scoped by RBAC).",
    permissions: ["hr.overtime.read", "hr.overtime.approve", "hr.overtime.create", "hr.attendance.team"],
    riskLevel: "read",
    dataClasses: ["hr_attendance", "hr_pii", "ops_summary"],
    intents: ["pending overtime", "OT pending", "overtime approvals", "approve OT"],
    examples: ["pending overtime", "OT pending today", "overtime queue"],
    preferDeterministic: true,
    handler: runOvertimeSummary,
  },
  {
    id: "hr.regularisation",
    toolId: "regularisation_summary",
    domain: "hr",
    label: "Regularisation queue",
    description: "Pending / approved / rejected attendance regularisation requests.",
    permissions: [
      "hr.regularisation.read",
      "hr.regularisation.approve",
      "hr.regularisation.create",
      "hr.attendance.team",
    ],
    riskLevel: "read",
    dataClasses: ["hr_attendance", "hr_pii", "ops_summary"],
    intents: ["pending regularisation", "regularisation queue", "fix attendance requests"],
    examples: ["pending regularisation", "regularisation queue"],
    preferDeterministic: true,
    handler: runRegularisationSummary,
  },
  {
    id: "hr.salary",
    toolId: "salary_summary",
    domain: "hr",
    label: "Salary / payroll",
    description: "Salary payments and payroll runs for a period (self or org by RBAC).",
    permissions: ["hr.salary.read", "hr.payslip.read", "hr.payslip.self"],
    riskLevel: "read",
    dataClasses: ["hr_pii", "finance_money"],
    intents: ["salary", "payroll", "payslip"],
    examples: ["salary this month", "my payslip", "payroll this week"],
    preferDeterministic: false,
    handler: runSalarySummary,
  },
  {
    id: "hr.advances",
    toolId: "staff_advances_summary",
    domain: "hr",
    label: "Staff advances",
    description:
      "Staff advance requests, approvals, issued amounts, pending settlement balances, and top staff rankings (self or org by RBAC).",
    permissions: ["staffadvance.read", "staffadvance.self.create", "staffadvance.self.settle"],
    riskLevel: "read",
    dataClasses: ["hr_pii", "finance_money"],
    intents: [
      "staff advances",
      "my advances",
      "advance balance",
      "pending advance approval",
      "pending advance settlement",
      "who took most advance",
    ],
    examples: [
      "staff advances",
      "my advances",
      "which staff requested most advance",
      "staff advance pending settlement",
    ],
    preferDeterministic: false,
    handler: runStaffAdvancesSummary,
  },
  {
    id: "hr.staff",
    toolId: "staff_summary",
    domain: "hr",
    label: "Staff master",
    description: "Active staff headcount by department with recent sample rows.",
    permissions: ["staff.read", "hr.employee.read"],
    riskLevel: "read",
    dataClasses: ["hr_pii", "ops_summary"],
    intents: ["staff", "employees", "headcount", "workforce"],
    examples: ["staff summary", "active employees", "headcount by department"],
    preferDeterministic: true,
    handler: runStaffSummary,
  },
  {
    id: "finance.sales",
    toolId: "sales_summary",
    domain: "finance",
    label: "Sales / billing",
    description: "Tax invoice sales totals for a period (and optional customer filter).",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["sales", "billing", "invoices", "tax invoices"],
    examples: ["today sales", "FY 26-27 sales", "Avaada sales this month"],
    preferDeterministic: false,
    handler: runSalesSummary,
  },
  {
    id: "finance.sales_orders",
    toolId: "sales_orders_summary",
    domain: "finance",
    label: "Sales orders",
    description: "Open sales-order queue and period order value (optional party/project filter).",
    permissions: ["salesorder.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["sales orders", "open SO", "SO pending"],
    examples: ["open sales orders", "SO pending"],
    preferDeterministic: true,
    handler: runSalesOrdersSummary,
  },
  {
    id: "finance.purchase_orders",
    toolId: "purchase_orders_summary",
    domain: "finance",
    label: "Purchase orders",
    description: "Open purchase-order queue and period PO value (optional vendor filter).",
    permissions: ["purchaseorder.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["purchase orders", "open PO", "POs"],
    examples: ["open purchase orders", "open POs"],
    preferDeterministic: true,
    handler: runPurchaseOrdersSummary,
  },
  {
    id: "finance.receipts",
    toolId: "receipts_summary",
    domain: "finance",
    label: "Receipts / collections",
    description: "Sales receipt collections totals for a period.",
    permissions: ["receipt.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["receipts", "collections", "money received"],
    examples: ["today receipts", "this month collections"],
    preferDeterministic: false,
    handler: runReceiptsSummary,
  },
  {
    id: "finance.payment_requests",
    toolId: "payment_requests_summary",
    domain: "finance",
    label: "Payment requests",
    description: "Payment requests awaiting action and paid-in-period counts.",
    permissions: ["paymentrequest.read", "paymentrequest.create"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["payment requests", "payments awaiting", "todays payment"],
    examples: ["payment requests pending", "todays payment"],
    preferDeterministic: true,
    handler: runPaymentRequestsSummary,
  },
  {
    id: "finance.entity_360",
    toolId: "entity_360",
    domain: "finance",
    label: "Entity 360 (record lookup)",
    description:
      "Cross-module consolidated summary for a specific record code (payment request C0028-P001-E002 / OTH/26-27/0011): parties, amount, purpose, project, approval chain, reconciliation, vendor beneficiary (RBAC-gated), and next actions.",
    permissions: ["paymentrequest.read", "paymentrequest.create"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["entity 360", "record lookup", "payment request details"],
    examples: [
      "C0028-P001-E002",
      "who posted OTH/26-27/0011",
      "details of payment request C0028-P001-VP001",
    ],
    preferDeterministic: true,
    handler: runEntity360,
  },
  {
    id: "finance.bank_recon",
    toolId: "bank_recon_summary",
    domain: "finance",
    label: "Bank reconciliation",
    description: "Unreconciled aging, statement uploads, and account balance presence.",
    permissions: ["bank.read", "bank.reconcile"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["bank recon", "reconciliation", "unreconciled"],
    examples: ["bank reconciliation", "unreconciled transactions"],
    preferDeterministic: true,
    handler: runBankReconSummary,
  },
  {
    id: "finance.receivables",
    toolId: "receivables_summary",
    domain: "finance",
    label: "Receivables / overdue",
    description: "Open and overdue sales invoice totals with party samples.",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["receivables", "overdue invoices", "outstanding"],
    examples: ["receivables", "overdue invoices"],
    preferDeterministic: false,
    handler: runReceivablesSummary,
  },
  {
    id: "finance.expenses",
    toolId: "staff_expense_summary",
    domain: "finance",
    label: "Staff expenses / reimbursements",
    description:
      "Paid manual expenses, reimbursement payment requests, posted staff-advance settlement expenses, staff-wise spend, and pending reimbursement requests.",
    permissions: ["accounts.dashboard.read", "accounts.read", "accounts.reports.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: [
      "expenses",
      "manual expenses",
      "staff expenses",
      "staff-wise expense report",
      "reimbursement requested by staff",
      "who claimed most reimbursement",
      "which staff spends more money",
    ],
    examples: [
      "expenses this month",
      "staff-wise expense report",
      "pending reimbursement for Arif",
      "who claimed most reimbursement",
    ],
    preferDeterministic: false,
    handler: runStaffExpenseSummary,
  },
  {
    id: "finance.accounts_snapshot",
    toolId: "accounts_snapshot",
    domain: "finance",
    label: "Accounts snapshot",
    description:
      "Journal/ledger structural counts and optional fund position (never invents TB/P&L/BS).",
    permissions: ["accounts.dashboard.read", "accounts.reports.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["accounts", "fund position", "journals", "chart of accounts"],
    examples: ["accounts snapshot", "fund position", "how many journals"],
    preferDeterministic: false,
    handler: runAccountsSnapshot,
  },
  {
    id: "finance.gstr_snapshot",
    toolId: "gstr_snapshot",
    domain: "finance",
    label: "GSTR snapshot",
    description: "Calendar-month GSTR-1 / GSTR-3B totals from report builders.",
    permissions: ["reports.read", "invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["gstr", "gstr1", "gstr3b", "gst return"],
    examples: ["gstr this month", "gstr3b", "gst return summary"],
    preferDeterministic: false,
    handler: runGstrSnapshot,
  },
  {
    id: "finance.director_dashboard",
    toolId: "director_dashboard_summary",
    domain: "finance",
    label: "Director dashboard",
    description: "Director / finance dashboard FY snapshot (same source as /director).",
    permissions: ["director.dashboard", "finance.dashboard.read", "accounts.dashboard.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["director dashboard", "finance dashboard", "command center"],
    examples: ["director dashboard", "finance snapshot this FY"],
    preferDeterministic: false,
    handler: runDirectorDashboardSummary,
  },
  {
    id: "finance.tally_status",
    toolId: "tally_status",
    domain: "finance",
    label: "Tally sync status",
    description: "Tally connection and recent sync job status (no invented TB/balances).",
    permissions: ["tally.dashboard.view"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "system_admin"],
    intents: ["tally", "tally sync", "tally status"],
    examples: ["tally status", "tally sync"],
    preferDeterministic: true,
    handler: runTallyStatus,
  },
  {
    id: "finance.order_book",
    toolId: "order_book_summary",
    domain: "finance",
    label: "Order book / FY target",
    description: "Confirmed project pipeline vs FY order-book target.",
    permissions: ["director.dashboard", "project.read", "salesorder.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["order book", "fy target", "pipeline"],
    examples: ["order book", "FY order book target"],
    preferDeterministic: false,
    handler: runOrderBookSummary,
  },
  {
    id: "finance.reports_snapshot",
    toolId: "reports_snapshot",
    domain: "finance",
    label: "Reports snapshot",
    description: "FY sales/collections/AR/AP report snapshot (real aggregates only).",
    permissions: ["reports.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["reports", "sales register", "aging", "AR aging"],
    examples: ["reports snapshot", "receivable aging", "sales register"],
    preferDeterministic: false,
    handler: runReportsSnapshot,
  },
  {
    id: "finance.gst_docs",
    toolId: "gst_docs_summary",
    domain: "finance",
    label: "GST docs (e-invoice / e-way)",
    description: "E-invoice and e-way bill status counts from compliance records.",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["e-invoice", "e-way", "gst docs"],
    examples: ["e-invoice status", "e-way bills"],
    preferDeterministic: true,
    handler: runGstDocsSummary,
  },
  {
    id: "finance.profitability",
    toolId: "profitability_summary",
    domain: "finance",
    label: "Project profitability",
    description: "All-time active + closed project P&L, loss-making projects, margin, and fund position.",
    permissions: ["project.profitability.view"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["profitability", "project pnl", "project profit", "project loss", "loss-making projects", "margin"],
    examples: ["project profitability", "project P&L", "any project at loss"],
    preferDeterministic: false,
    handler: runProfitabilitySummary,
  },
  {
    id: "finance.overdue_invoices",
    toolId: "overdue_invoices",
    domain: "finance",
    label: "Overdue invoices",
    description: "Overdue / past-due sales invoices with party samples.",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["overdue invoices", "past due", "overdue billing"],
    examples: ["overdue invoices", "past due invoices"],
    preferDeterministic: true,
    handler: runOverdueInvoices,
  },
  {
    id: "finance.collection_delay_estimate",
    toolId: "collection_delay_estimate",
    domain: "finance",
    label: "Collection delay estimate",
    description:
      "Labeled prediction heuristic from overdue age buckets — never ledger truth; honest empty without facts.",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["collection delay", "payment delay risk", "when will they pay"],
    examples: ["collection delay estimate", "payment delay prediction"],
    preferDeterministic: true,
    handler: runCollectionDelayEstimate,
  },
  {
    id: "finance.purchase_bills",
    toolId: "purchase_bills_summary",
    domain: "finance",
    label: "Purchase bills",
    description: "Purchase bill totals and pending-approval counts for a period.",
    permissions: ["purchasebill.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["purchase bills", "vendor invoices", "bills pending"],
    examples: ["purchase bills this month", "pending purchase bills"],
    preferDeterministic: false,
    handler: runPurchaseBillsSummary,
  },
  {
    id: "finance.bank_accounts",
    toolId: "bank_accounts_summary",
    domain: "finance",
    label: "Bank accounts",
    description: "Active bank accounts with optional book/statement/operational totals.",
    permissions: ["bank.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["bank accounts", "bank balance", "total bank"],
    examples: ["bank accounts", "total bank balance"],
    preferDeterministic: true,
    handler: runBankAccountsSummary,
  },
  {
    id: "finance.credit_notes",
    toolId: "credit_notes_summary",
    domain: "finance",
    label: "Credit / debit notes",
    description: "Sales credit and debit note totals for a period.",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["credit notes", "debit notes", "CN"],
    examples: ["credit notes this month", "debit notes"],
    preferDeterministic: false,
    handler: runCreditNotesSummary,
  },
  {
    id: "finance.customer_outstanding",
    toolId: "customer_outstanding",
    domain: "finance",
    label: "Customer outstanding",
    description: "Customer receivables / pending payments from clients (invoice AR, optional party filter).",
    permissions: ["invoice.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["customer outstanding", "party outstanding", "AR by customer", "client pending payment", "payment receivable from client"],
    examples: ["customer outstanding", "Avaada outstanding", "payment receivable from client"],
    preferDeterministic: false,
    handler: runCustomerOutstanding,
  },
  {
    id: "finance.vendors",
    toolId: "vendors_summary",
    domain: "finance",
    label: "Vendors master",
    description: "Vendor headcount and recent vendors (optional name filter).",
    permissions: ["vendor.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["vendors", "supplier list", "vendor master"],
    examples: ["vendors", "active vendors", "vendor summary"],
    preferDeterministic: true,
    handler: runVendorsSummary,
  },
  {
    id: "finance.customers",
    toolId: "customers_summary",
    domain: "finance",
    label: "Customers master",
    description: "Customer headcount and recent customers (optional name filter).",
    permissions: ["customer.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["customers", "customer list", "customer master"],
    examples: ["customers", "active customers", "customer summary"],
    preferDeterministic: true,
    handler: runCustomersSummary,
  },
  {
    id: "finance.purchase_requests",
    toolId: "purchase_requests_summary",
    domain: "finance",
    label: "Purchase requests queue",
    description: "Pending purchase requests (draft / submitted / manager verified).",
    permissions: ["purchaserequest.read", "purchaserequest.create"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money"],
    intents: ["purchase requests", "pending PR", "indent pending"],
    examples: ["pending purchase requests", "purchase request queue"],
    preferDeterministic: true,
    handler: runPurchaseRequestsSummary,
  },
  {
    id: "finance.cbg_quotations",
    toolId: "cbg_quotations_summary",
    domain: "finance",
    label: "CBG quotations",
    description: "CBG quotation counts and recent samples for a period.",
    permissions: ["cbgquotation.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: ["cbg quotations", "quotations", "cbg quotes"],
    examples: ["cbg quotations this month", "quotations"],
    preferDeterministic: false,
    handler: runCbgQuotationsSummary,
  },
  {
    id: "ops.kpi",
    toolId: "kpi_summary",
    domain: "ops",
    label: "KPI scores",
    description: "Latest KPI period scores (self / team / org / named person).",
    permissions: ["kpi.read.all", "kpi.read.team", "kpi.read.self"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "hr_pii"],
    intents: ["kpi", "kpi score", "kpi list"],
    examples: ["kpi list", "my kpi"],
    preferDeterministic: false,
    handler: runKpiSummary,
  },
  {
    id: "ops.kpi_report",
    toolId: "kpi_report",
    domain: "ops",
    label: "KPI report card",
    description:
      "Detailed KPI report card — why score is high/low, contributing factors, formula, trend.",
    permissions: ["kpi.read.all", "kpi.read.team", "kpi.read.self"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "hr_pii"],
    intents: [
      "kpi report",
      "kpi report card",
      "why is kpi low",
      "why is kpi high",
      "explain kpi",
      "kpi breakdown",
    ],
    examples: [
      "why is my kpi low",
      "kpi report card",
      "explain Amit kpi",
      "why is Priya kpi high",
    ],
    preferDeterministic: true,
    handler: runKpiReport,
  },
  {
    id: "ops.incentives",
    toolId: "incentives_summary",
    domain: "ops",
    label: "Incentives",
    description: "Staff incentives open / unpaid (self / team / org by RBAC).",
    permissions: ["incentive.read.all", "incentive.read.team", "incentive.read.self"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "hr_pii", "finance_money"],
    intents: ["incentives", "bonus", "incentive payment"],
    examples: ["incentives this month", "pending incentives"],
    preferDeterministic: true,
    handler: runIncentivesSummary,
  },
  {
    id: "ops.tasks",
    toolId: "tasks_summary",
    domain: "ops",
    label: "Tasks",
    description: "Open / overdue / completed tasks for self, team, or named person.",
    permissions: ["task.read.self", "task.edit.team", "task.admin"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["tasks", "todo", "overdue tasks"],
    examples: ["my tasks", "overdue tasks", "Zeeshan tasks"],
    preferDeterministic: true,
    handler: runTasksSummary,
  },
  {
    id: "ops.my_work",
    toolId: "my_work_summary",
    domain: "ops",
    label: "My work snapshot",
    description: "Session user's open tasks, KPI, and pending leave in one pack.",
    permissions: ["task.read.self", "kpi.read.self", "hr.leave.create"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "hr_pii"],
    intents: ["my work", "what do I have"],
    examples: ["my work", "what should I do"],
    preferDeterministic: true,
    handler: runMyWorkSummary,
  },
  {
    id: "ops.stock",
    toolId: "stock_summary",
    domain: "ops",
    label: "Stock",
    description: "Active items, movements, and below-minimum stock.",
    permissions: ["stock.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["stock", "inventory", "low stock"],
    examples: ["stock summary", "low stock"],
    preferDeterministic: true,
    handler: runStockSummary,
  },
  {
    id: "ops.grn",
    toolId: "grn_summary",
    domain: "ops",
    label: "GRN / material receipts",
    description: "Material receipt (GRN) counts for a period with sample rows.",
    permissions: ["stock.read", "purchaseorder.read", "purchaserequest.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["grn", "material receipts", "goods receipt"],
    examples: ["grn this month", "material receipts"],
    preferDeterministic: true,
    handler: runGrnSummary,
  },
  {
    id: "ops.pending_workflow",
    toolId: "pending_workflow_counts",
    domain: "ops",
    label: "Pending workflow counts",
    description: "Cross-module pending counts: payment requests, purchase bills, approvals.",
    permissions: [
      "paymentrequest.read",
      "purchasebill.read",
      "approval.read.self",
      "approval.read.team",
      "approval.read.all",
    ],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money"],
    intents: ["pending workflow", "what's pending", "awaiting action"],
    examples: ["pending workflow", "what is pending"],
    preferDeterministic: true,
    handler: runPendingWorkflowCounts,
  },
  {
    id: "ops.approvals",
    toolId: "approvals_summary",
    domain: "ops",
    label: "Approvals queue",
    description: "Open approval requests in the caller's RBAC scope.",
    permissions: ["approval.read.self", "approval.read.team", "approval.read.all"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money"],
    intents: ["approvals", "pending approvals", "open approvals"],
    examples: ["pending approvals", "open approvals"],
    preferDeterministic: true,
    handler: runApprovalsSummary,
  },
  {
    id: "ops.delivery",
    toolId: "delivery_summary",
    domain: "ops",
    label: "Delivery / installation",
    description:
      "DeliveryRecord stage/date summaries for delivery, dispatch, delivered, installation, delays, and engineer/vendor responsibility.",
    permissions: ["delivery.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: [
      "pending delivery",
      "delayed deliveries",
      "dispatched / shipped",
      "delivered",
      "installation pending",
      "installation delayed",
      "installation completed",
      "who handled delivery / installation",
    ],
    examples: [
      "pending delivery for Avaada",
      "delayed deliveries",
      "what is delivered for project C0001-P001",
      "installation completed this week",
      "who handled installation for James School",
    ],
    preferDeterministic: true,
    handler: runDeliverySummary,
  },
  {
    id: "ops.projects",
    toolId: "projects_summary",
    domain: "ops",
    label: "Projects",
    description: "Active project counts and contract values for the Indian FY.",
    permissions: ["project.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["projects", "project value", "active projects"],
    examples: ["projects this FY", "project value"],
    preferDeterministic: false,
    handler: runProjectsSummary,
  },
  {
    id: "system.documents_open",
    toolId: "documents_open",
    domain: "system",
    label: "Documents hub",
    description: "Deep-link to Documents with vault counts (no file bodies).",
    permissions: ["documents.read"],
    riskLevel: "read",
    dataClasses: ["documents"],
    intents: ["documents", "files", "vault"],
    examples: ["documents", "files"],
    preferDeterministic: true,
    handler: runDocumentsOpen,
  },
  {
    id: "system.documents_search",
    toolId: "documents_search",
    domain: "system",
    label: "Document search",
    description:
      "Permission-filtered document metadata search with citations (no file bodies; DB wins on money).",
    permissions: ["documents.read"],
    riskLevel: "read",
    dataClasses: ["documents"],
    intents: ["search documents", "find file", "document attachment"],
    examples: ["search documents contract", "find PDF for Avaada"],
    preferDeterministic: true,
    handler: runDocumentsSearch,
  },
  {
    id: "system.nova_pulse_search",
    toolId: "nova_pulse_search",
    domain: "system",
    label: "NOVA Pulse (what changed)",
    description:
      "Search recorded ERP change events (task assign/complete/cancel/uploads). Read-only; never invents activity.",
    permissions: ["task.read.self", "documents.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "documents"],
    intents: [
      "what changed",
      "any changes",
      "pulse",
      "files uploaded on task",
      "task changes assigned by me",
    ],
    examples: [
      "any changes in tasks assigned by me",
      "Zeeshan's task any files uploaded",
      "what changed on my tasks this week",
    ],
    preferDeterministic: true,
    handler: runNovaPulseSearch,
  },
  {
    id: "system.settings_open",
    toolId: "settings_open",
    domain: "system",
    label: "Settings",
    description: "Deep-link to Settings with safe company meta (no secrets).",
    permissions: ["settings.write"],
    riskLevel: "read",
    dataClasses: ["system_admin", "public_meta"],
    intents: ["settings", "company settings"],
    examples: ["settings"],
    preferDeterministic: true,
    handler: runSettingsOpen,
  },
  {
    id: "system.appearance_open",
    toolId: "appearance_open",
    domain: "system",
    label: "Appearance",
    description: "Deep-link to personal Appearance (theme / language).",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["public_meta"],
    intents: ["appearance", "theme", "dark mode"],
    examples: ["appearance", "theme settings"],
    preferDeterministic: true,
    handler: runAppearanceOpen,
  },
  {
    id: "system.vendor_bank_open",
    toolId: "vendor_bank_open",
    domain: "system",
    label: "Vendor bank details",
    description: "Deep-link to Vendors with bank-detail presence counts (no identifiers).",
    permissions: ["vendorbank.read", "bank.viewfullaccount"],
    riskLevel: "read",
    dataClasses: ["finance_money", "system_admin"],
    intents: ["vendor bank", "beneficiary details"],
    examples: ["vendor bank details"],
    preferDeterministic: true,
    handler: runVendorBankOpen,
  },
  {
    id: "system.notifications_open",
    toolId: "notifications_open",
    domain: "system",
    label: "Notifications",
    description: "Deep-link to Notifications with unread count (no message bodies).",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["public_meta"],
    intents: ["notifications", "alerts", "inbox"],
    examples: ["notifications", "unread alerts"],
    preferDeterministic: true,
    handler: runNotificationsOpen,
  },
  {
    id: "system.whatsapp_open",
    toolId: "whatsapp_open",
    domain: "system",
    label: "WhatsApp",
    description: "Deep-link to WhatsApp (no invented message contents).",
    permissions: ["whatsapp.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["whatsapp"],
    examples: ["whatsapp"],
    preferDeterministic: true,
    handler: runWhatsappOpen,
  },
  {
    id: "system.portal_open",
    toolId: "portal_open",
    domain: "system",
    label: "Portal",
    description: "Deep-link to Portal.",
    permissions: ["portal.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["portal"],
    examples: ["portal"],
    preferDeterministic: true,
    handler: runPortalOpen,
  },
  {
    id: "system.automation_open",
    toolId: "automation_open",
    domain: "system",
    label: "Automation",
    description: "Deep-link to Automation (no invented stats).",
    permissions: ["automation.read"],
    riskLevel: "read",
    dataClasses: ["system_admin"],
    intents: ["automation"],
    examples: ["automation"],
    preferDeterministic: true,
    handler: runAutomationOpen,
  },
  {
    id: "system.links_open",
    toolId: "links_open",
    domain: "system",
    label: "Links",
    description: "Deep-link to the shared link library.",
    permissions: ["links.read"],
    riskLevel: "read",
    dataClasses: ["public_meta"],
    intents: ["links"],
    examples: ["links"],
    preferDeterministic: true,
    handler: runLinksOpen,
  },
  {
    id: "system.bank_sms_open",
    toolId: "bank_sms_open",
    domain: "system",
    label: "Bank SMS",
    description: "Deep-link to Bank SMS (no invented balances or account numbers).",
    permissions: ["bank.sms.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["bank sms", "sms entries"],
    examples: ["bank sms"],
    preferDeterministic: true,
    handler: runBankSmsOpen,
  },
  {
    id: "system.backup_open",
    toolId: "backup_open",
    domain: "system",
    label: "System Backup",
    description: "Deep-link to System Backup history (no create/download/restore).",
    permissions: ["backup.read"],
    riskLevel: "read",
    dataClasses: ["system_admin"],
    intents: ["backup", "system backup"],
    examples: ["backup"],
    preferDeterministic: true,
    handler: runBackupOpen,
  },
  {
    id: "system.system_tools_open",
    toolId: "system_tools_open",
    domain: "system",
    label: "System Tools",
    description: "Deep-link to System Tools for Admin / Super Admin / Director.",
    permissions: ["system.tools"],
    riskLevel: "read",
    dataClasses: ["system_admin"],
    intents: ["system tools"],
    examples: ["system tools"],
    preferDeterministic: true,
    handler: runSystemToolsOpen,
  },
  {
    id: "system.audit_log_open",
    toolId: "audit_log_open",
    domain: "system",
    label: "Audit Log",
    description: "Deep-link to Audit Log (no row listing in chat).",
    permissions: ["audit.read"],
    riskLevel: "read",
    dataClasses: ["system_admin"],
    intents: ["audit log", "audit"],
    examples: ["audit log"],
    preferDeterministic: true,
    handler: runAuditLogOpen,
  },
  {
    id: "ops.daily_brief",
    toolId: "daily_brief",
    domain: "ops",
    label: "Daily brief",
    description: "Role-aware read-only brief composing existing registered skills (no writes).",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money", "hr_attendance", "hr_pii"],
    intents: ["daily brief", "morning brief", "role brief", "today brief"],
    examples: ["daily brief", "morning brief", "my brief today"],
    preferDeterministic: true,
    handler: runDailyBrief,
  },
  {
    id: "ops.proactive_insights",
    toolId: "proactive_insights",
    domain: "ops",
    label: "Proactive insights",
    description:
      "Read-only insight cards (overdue AR, approvals, payroll blockers, stock, projects, GST, backup/Tally) with Finding provenance — no writes.",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money", "hr_attendance"],
    intents: ["insights", "proactive insights", "what needs attention", "attention queue"],
    examples: ["proactive insights", "what needs attention", "insight cards"],
    preferDeterministic: true,
    handler: runProactiveInsights,
  },
  {
    id: "ops.nova_analysis",
    toolId: "nova_analysis",
    domain: "ops",
    label: "NOVA Analysis",
    description:
      "Why-is-it-here reasoning: catalog skill fact packs (KPI report-card, overdue tasks, AR, attendance, project) + LLM synthesis. Never invents numbers; RBAC via domain skills.",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money", "hr_attendance", "hr_pii"],
    intents: [
      "why is my kpi low",
      "why overdue",
      "analyze this project",
      "why outstanding",
      "attendance analysis",
    ],
    examples: [
      "why is my kpi low",
      "why overdue",
      "analyze this project",
      "why is outstanding high",
      "why so many late",
    ],
    preferDeterministic: true,
    handler: runNovaAnalysisSkill,
  },
  {
    id: "ops.nova_trend",
    toolId: "nova_trend",
    domain: "ops",
    label: "NOVA Trend",
    description:
      "Universal measurable trends: late-comers, late task completion, KPI score / high streak, AR aging, …. Series + rankings with domain ACL — not money-only.",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "hr_attendance", "hr_pii", "finance_money"],
    intents: [
      "who is frequently late",
      "late comers trend",
      "late trend",
      "over time",
      "who completes tasks after overdue",
      "ar aging trend",
      "employee expense trend",
      "staff spend trend",
      "kpi trend",
      "high kpi streak",
      "nova trend",
    ],
    examples: [
      "late comers trend last 30 days",
      "who is frequently late",
      "late punch trend last 30 days",
      "who completes tasks after overdue most often",
      "KPI trend for Amit this quarter",
      "who has high KPI for a long streak",
      "AR aging trend last 90 days",
      "customers whose outstanding is worsening",
      "employee expense trend last 3 months",
    ],
    preferDeterministic: true,
    handler: runNovaTrendSkill,
  },
  {
    id: "finance.collection_attention",
    toolId: "collection_attention",
    domain: "finance",
    label: "Collection attention",
    description:
      "Named pack #3: customer outstanding + overdue + receipts (facts only; not payment risk).",
    permissions: ["invoice.read", "receipt.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["collection attention", "collections focus", "outstanding and overdue"],
    examples: [
      "collection attention for Avaada",
      "outstanding and overdue for Miura",
      "Collection attention",
    ],
    preferDeterministic: true,
    handler: runCollectionAttentionPackRecipe,
  },
  {
    id: "finance.month_performance",
    toolId: "month_performance",
    domain: "finance",
    label: "Director Month Performance",
    description:
      "Named pack #1: period-explicit month summary with ≤3 attentions and governed KPI/trend/ageing charts.",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["finance_money", "ops_summary"],
    intents: [
      "month performance",
      "how is this month going",
      "director brief",
      "how is july going",
    ],
    examples: [
      "How is this month going?",
      "Month performance",
      "Director brief for this month",
    ],
    preferDeterministic: true,
    handler: runMonthPerformanceRecipe,
  },
  {
    id: "hr.attendance_month",
    toolId: "attendance_month",
    domain: "hr",
    label: "Attendance Month",
    description:
      "Savable HR month pack: present/late/absent overview with ≤3 attentions (register facts only).",
    permissions: ["hr.attendance.read", "hr.attendance.team", "hr.punch.self"],
    riskLevel: "read",
    dataClasses: ["hr_attendance", "hr_pii"],
    intents: [
      "how is this month attendance",
      "attendance this month",
      "month attendance",
    ],
    examples: [
      "how is this month's attendance?",
      "how is this month attendance",
      "attendance this month",
    ],
    preferDeterministic: true,
    handler: runAttendanceMonthRecipe,
  },
  {
    id: "finance.cash_banking",
    toolId: "cash_banking",
    domain: "finance",
    label: "Cash / Banking",
    description:
      "Savable cash pack: bank position + receipts + recon + payment requests (≤3 attentions).",
    permissions: ["bank.read"],
    riskLevel: "read",
    dataClasses: ["finance_money"],
    intents: ["how is cash", "cash position", "bank balances", "cash and banking"],
    examples: [
      "how is cash this week?",
      "cash and banking this month",
      "bank balances",
      "cash position",
    ],
    preferDeterministic: true,
    handler: runCashBankingRecipe,
  },
  {
    id: "finance.cbg_pipeline",
    toolId: "cbg_pipeline",
    domain: "finance",
    label: "CBG pipeline",
    description: "CBG quotation status funnel (facts only).",
    permissions: ["cbgquotation.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["CBG pipeline", "CBG funnel"],
    examples: ["CBG pipeline", "CBG status breakdown"],
    preferDeterministic: true,
    handler: runCbgPipelineRecipe,
  },
  {
    id: "ops.project_health",
    toolId: "project_health",
    domain: "ops",
    label: "Project health",
    description:
      "Project-scoped ERP facts when available; honest gap when scopedFacts missing (no attendance-by-project).",
    permissions: ["project.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary"],
    intents: ["project health"],
    examples: ["project health for Tata plant"],
    preferDeterministic: true,
    handler: runProjectHealthRecipe,
  },
  {
    id: "ops.project_command",
    toolId: "project_command",
    domain: "ops",
    label: "Project Command",
    description:
      "Named pack #2: tell me everything important about this project — SO/PO/delivery/invoice/cash/tasks.",
    permissions: ["project.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "finance_money"],
    intents: [
      "project command",
      "everything important about this project",
      "tell me about this project",
    ],
    examples: [
      "tell me everything important about this project",
      "Project Command for Tata plant",
    ],
    preferDeterministic: true,
    handler: runProjectCommandRecipe,
  },
  {
    id: "meta.search_entities",
    toolId: "search_entities",
    domain: "meta",
    label: "Entity search",
    description: "Permission-aware business-data search (customers, vendors, projects, …).",
    permissions: ["ai.assistant.read"],
    riskLevel: "read",
    dataClasses: ["ops_summary", "public_meta"],
    intents: ["search", "find", "lookup"],
    examples: ["find Avaada", "search vendor"],
    preferDeterministic: false,
    handler: runSearchEntities,
  },
];

/** Skill metadata permissions always mirror `NOVA_TOOL_PERMISSIONS` (NI-01). */
const SKILLS: NovaSkill[] = SKILLS_DEFS.map((s) => ({
  ...s,
  permissions: novaPermissionsForTool(s.toolId),
}));

const BY_TOOL_ID = new Map(SKILLS.map((s) => [s.toolId, s]));

export function listNovaSkills(): readonly NovaSkill[] {
  return SKILLS;
}

export function getNovaSkill(toolId: string): NovaSkill | undefined {
  return BY_TOOL_ID.get(toolId);
}

export function hasNovaSkill(toolId: string): boolean {
  return BY_TOOL_ID.has(toolId);
}

export function listNovaSkillToolIds(): string[] {
  return SKILLS.map((s) => s.toolId);
}

/** Skills that must skip free LLM list narration (deterministic formatter). */
export function novaSkillPrefersDeterministic(toolId: string): boolean {
  return BY_TOOL_ID.get(toolId)?.preferDeterministic === true;
}

/** Union of data classes across selected tool ids (for LLM provider routing). */
export function novaDataClassesForTools(toolIds: string[]): NovaSkill["dataClasses"] {
  const out = new Set<NovaSkill["dataClasses"][number]>();
  for (const id of toolIds) {
    const skill = BY_TOOL_ID.get(id);
    if (!skill) continue;
    for (const dc of skill.dataClasses) out.add(dc);
  }
  return [...out];
}

export async function dispatchNovaSkill(
  toolId: string,
  ctx: NovaSkillHandlerContext
): Promise<NovaSkillHandlerResult | null> {
  const skill = BY_TOOL_ID.get(toolId);
  if (!skill) return null;
  return skill.handler(ctx);
}

export type { NovaSkill, NovaSkillHandlerContext, NovaSkillHandlerResult };
